name = "PDESystemLibrary"
uuid = "d14f9848-fe58-4297-bd22-c1aba6f3000d"
authors = ["Alex Jones (xtalax) <alex.jones@xisoft.co.uk> and contributors"]
version = "0.1.1"

[deps]
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
IfElse = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

[compat]
DomainSets = "0.5, 0.6"
IfElse = "0.1.0"
Interpolations = "0.14"
Markdown = "1"
ModelingToolkit = "8.48"
OrdinaryDiffEq = "6"
SciMLBase = "1.88"
julia = "1.6"

[extras]
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MethodOfLines = "94925ecb-adb7-4558-8ed8-f975c56a0bf4"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "MethodOfLines", "Lux", "NonlinearSolve", "OptimizationOptimJL", "SafeTestsets"]
